const enumUsersRoles = {
    PARTICIPANT: "PARTICIPANT",
    STAGIAIRE: "STAGIAIRE",
    DOCTORANT: "DOCTORANT",
    CHEFDEPROJET: "CHEFPROJET",
    BAILLEUR: "BAILLEUR",
    CHERCHEUR: "CHERCHEUR",
    ADMIN: "ADMIN",
    EDITOR: "EDITOR",
    SUPERADMIN: "SUPERADMIN",
};

module.exports = enumUsersRoles;
